services:
  database:
    class: "App\\Model\\Database"
    params:
      dsn: "@database.dsn"
      username: "@database.username"
      password: "@database.password"
  passwordHasher:
    class: "App\\Service\\PasswordHasher"
